Repository mbridak/not1mm, pull requests merged in 2024-10, with the labels that each got.

#156 MST Removed leading zeros on serial numbers
  not1mm/plugins/icwc_mst.py
Labels: enhancement request

#157 cwt fixed error on duplicate entry in cwt
  not1mm/plugins/cwt.py
Labels: bug

#159 @mbridak Update key help dialog.
  README.md
  not1mm/__main__.py
Labels: documentation

#160 @mbridak Extend splash screen use.
  not1mm/__main__.py
Labels: enhancement

#163 Force reselction of contest after different DB opened.
  not1mm/__main__.py
Labels: bug

#164 @mbridak Store the bandmap spots age timer in the preferences.
  CHANGELOG.md
  README.md
  not1mm/__main__.py
  not1mm/bandmap.py
  not1mm/lib/version.py
  pyproject.toml
Labels: enhancement

#165 Automated Testing
  not1mm/__main__.py
  not1mm/lib/multicast.py
  not1mm/plugins/cq_wpx_rtty.py
  not1mm/plugins/cq_ww_rtty.py
  test/contests.py
Labels: bug

#167 @mbridak Fix crash on Tune to spot. Change placeholder text for the C…
  CHANGELOG.md
  README.md
  not1mm/__main__.py
  not1mm/lib/settings.py
  not1mm/lib/version.py
  pyproject.toml
Labels: bug

#169 Esm or redacted due to swear words
  not1mm/__main__.py
  not1mm/data/configuration.ui
  not1mm/lib/settings.py
  not1mm/plugins/cq_ww_cw.py
Labels: enhancement

#170 @mbridak Add ESM to CQWW ssb and rtty.
  not1mm/__main__.py
  not1mm/plugins/cq_ww_rtty.py
  not1mm/plugins/cq_ww_ssb.py
Labels: enhancement

#178 @mbridak Allow slashes in callsign during ESM check.
  not1mm/plugins/cq_wpx_cw.py
  not1mm/plugins/cq_wpx_rtty.py
  not1mm/plugins/cq_wpx_ssb.py
  not1mm/plugins/cq_ww_cw.py
  not1mm/plugins/cq_ww_rtty.py
  not1mm/plugins/cq_ww_ssb.py
  not1mm/plugins/cwt.py
  not1mm/plugins/k1usn_sst.py
  not1mm/plugins/naqp_cw.py
  not1mm/plugins/naqp_rtty.py
  not1mm/plugins/naqp_ssb.py
  not1mm/plugins/weekly_rtty.py
  not1mm/testing/multicast_listener.py
Labels: bug

#182 @mbridak Fix the time of the marked spot in the bandmap.
  not1mm/bandmap.py
Labels: bug

#185 Recheck esm state on run sandp toggle
  CHANGELOG.md
  README.md
  not1mm/__main__.py
  not1mm/lib/version.py
  not1mm/plugins/arrl_field_day.py
  not1mm/plugins/winter_field_day.py
  pyproject.toml
Labels: enhancement

#186 Rewrite cat control be bold be brave
  not1mm/__main__.py
  not1mm/lib/cat_interface.py
  not1mm/radio.py
Labels: enhancement

#188 187 widgets fail to update when there is no network connection
  CHANGELOG.md
  README.md
  not1mm/__main__.py
  not1mm/bandmap.py
  not1mm/checkwindow.py
  not1mm/lib/version.py
  not1mm/logwindow.py
  not1mm/lookupservice.py
  pyproject.toml
Labels: bug

#190 @mbridak OOpsie
  not1mm/bandmap.py
Labels: bug

#191 Multi marked to single marked
  CHANGELOG.md
  README.md
  not1mm/bandmap.py
  not1mm/lib/version.py
  pyproject.toml
Labels: bug

#192 Forgot about the vfo window
  CHANGELOG.md
  README.md
  not1mm/__main__.py
  not1mm/lib/version.py
  not1mm/vfo.py
  pyproject.toml
Labels: bug

#194 Make cabrillo use utf 8
  CHANGELOG.md
  README.md
  not1mm/lib/version.py
  not1mm/plugins/10_10_fall_cw.py
  not1mm/plugins/10_10_spring_cw.py
  not1mm/plugins/10_10_summer_phone.py
  not1mm/plugins/10_10_winter_phone.py
  not1mm/plugins/arrl_10m.py
  not1mm/plugins/arrl_dx_cw.py
  not1mm/plugins/arrl_dx_ssb.py
  not1mm/plugins/arrl_field_day.py
  not1mm/plugins/arrl_ss_cw.py
  not1mm/plugins/arrl_ss_phone.py
  not1mm/plugins/arrl_vhf_jan.py
  not1mm/plugins/arrl_vhf_jun.py
  not1mm/plugins/arrl_vhf_sep.py
  not1mm/plugins/canada_day.py
  not1mm/plugins/cq_160_cw.py
  not1mm/plugins/cq_160_ssb.py
  not1mm/plugins/cq_wpx_cw.py
  not1mm/plugins/cq_wpx_rtty.py
  not1mm/plugins/cq_wpx_ssb.py
  not1mm/plugins/cq_ww_cw.py
  not1mm/plugins/cq_ww_rtty.py
  not1mm/plugins/cq_ww_ssb.py
  not1mm/plugins/cwt.py
  not1mm/plugins/helvetia.py
  not1mm/plugins/iaru_fieldday_r1_cw.py
  not1mm/plugins/iaru_fieldday_r1_ssb.py
  not1mm/plugins/iaru_hf.py
  not1mm/plugins/icwc_mst.py
  not1mm/plugins/jidx_cw.py
  not1mm/plugins/jidx_ph.py
  not1mm/plugins/k1usn_sst.py
  not1mm/plugins/naqp_cw.py
  not1mm/plugins/naqp_rtty.py
  not1mm/plugins/naqp_ssb.py
  not1mm/plugins/phone_weekly_test.py
  not1mm/plugins/ref_cw.py
  not1mm/plugins/ref_ssb.py
  not1mm/plugins/stew_perry_topband.py
  not1mm/plugins/weekly_rtty.py
  not1mm/plugins/winter_field_day.py
  pyproject.toml
Labels: bug

#196 Your choice ascii or utf
  CHANGELOG.md
  README.md
  not1mm/__main__.py
  not1mm/data/main.ui
  not1mm/lib/version.py
  not1mm/plugins/10_10_fall_cw.py
  not1mm/plugins/10_10_spring_cw.py
  not1mm/plugins/10_10_summer_phone.py
  not1mm/plugins/10_10_winter_phone.py
  not1mm/plugins/arrl_10m.py
  not1mm/plugins/arrl_dx_cw.py
  not1mm/plugins/arrl_dx_ssb.py
  not1mm/plugins/arrl_field_day.py
  not1mm/plugins/arrl_ss_cw.py
  not1mm/plugins/arrl_ss_phone.py
  not1mm/plugins/arrl_vhf_jan.py
  not1mm/plugins/arrl_vhf_jun.py
  not1mm/plugins/arrl_vhf_sep.py
  not1mm/plugins/canada_day.py
  not1mm/plugins/cq_160_cw.py
  not1mm/plugins/cq_160_ssb.py
  not1mm/plugins/cq_wpx_cw.py
  not1mm/plugins/cq_wpx_rtty.py
  not1mm/plugins/cq_wpx_ssb.py
  not1mm/plugins/cq_ww_cw.py
  not1mm/plugins/cq_ww_rtty.py
  not1mm/plugins/cq_ww_ssb.py
  not1mm/plugins/cwt.py
  not1mm/plugins/general_logging.py
  not1mm/plugins/helvetia.py
  not1mm/plugins/iaru_fieldday_r1_cw.py
  not1mm/plugins/iaru_fieldday_r1_ssb.py
  not1mm/plugins/iaru_hf.py
  not1mm/plugins/icwc_mst.py
  not1mm/plugins/jidx_cw.py
  not1mm/plugins/jidx_ph.py
  not1mm/plugins/k1usn_sst.py
  not1mm/plugins/naqp_cw.py
  not1mm/plugins/naqp_rtty.py
  not1mm/plugins/naqp_ssb.py
  not1mm/plugins/phone_weekly_test.py
  not1mm/plugins/ref_cw.py
  not1mm/plugins/ref_ssb.py
  not1mm/plugins/stew_perry_topband.py
  not1mm/plugins/weekly_rtty.py
  not1mm/plugins/winter_field_day.py
  pyproject.toml
Labels: enhancement

#201 Couple personal annoyances
  not1mm/__main__.py
  not1mm/bandmap.py
Labels: bug, enhancement

#202 @mbridak Drop Beacons from bandmap.
  not1mm/bandmap.py
Labels: enhancement

#204 @mbridak dict received another dict object instead of a copy of the d…
  CHANGELOG.md
  README.md
  not1mm/__main__.py
  not1mm/lib/version.py
  pyproject.toml
Labels: bug

#205 Fix ssb modes send to radio when crossing between the 10M boundary.
  CHANGELOG.md
  README.md
  not1mm/__main__.py
  not1mm/lib/version.py
  pyproject.toml
Labels: bug

#206 @mbridak Allow undocking widgets while using Wayland if PyQt6 version…
  CHANGELOG.md
  README.md
  not1mm/__main__.py
  not1mm/lib/version.py
  pyproject.toml
Labels: enhancement
